In [21]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'

device

'cuda'

In [24]:
start_time = time.time()

zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
elapsed_time
print(f"{elapsed_time:.14f}")

0.00000000000000


In [4]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-59,  58,   5, -29, -35, -78])

In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [9]:
zeros = torch.zeros(2, 6)
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [16]:
linspace = torch.linspace(0, 10, steps=5)
linspace

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [17]:
logspace = torch.logspace(start=0, end=10, steps=5)
logspace

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10])

In [18]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])